---
title: Royal Society DELVE Initiative
timezone: UTC
collections:
  addenda:
    title: Addenda
    output: true
    permalink: "/addenda/:year/:month/:day/:title:output_ext"
  data_software:
    title: Data & Software
    output: true
    permalink: "/data_software/:title:output_ext"
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  reports:
    title: Reports
    output: true
    permalink: "/reports/:year/:month/:day/:title:output_ext"
  uploads:
    title: Uploads
    output: true
logo: logo.png
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
description: This is the GitHub Repository of the DELVE Initiative convened by the
  Royal Society as a multidisciplinary group of scientists, statisticians, economists,
  public health experts to provide independent policy advice on the COVID-19 pandemic.
baseurl: ''
url: http://rs-delve.github.io
markdown: kramdown
github_username: rs-delve
display:
  copy_button:
    bibtex: false
    endnote: false
    apa: false
    ris: false
  comments: false
ghub:
  edit: true
  repository: rs-delve.github.io
future: true
publisher: The Royal Society
author:
  name: Royal Society DELVE Initiative
  github: rs-delve
